#
# This file is automatically generated by the Terraform inventory module
#
---
all:
  hosts:
%{ for cluster, hostinfo in crdb_servers ~} %{ for index, ip in hostinfo.ips ~}
    ${ip}:
      hostname_short: ${ hostinfo.hostnames_short[index] }
      hostname_long: ${ hostinfo.hostnames_long[index] }
%{ endfor ~}%{ endfor ~}
%{ for cluster, hostinfo in crdb_client_servers ~}%{ for index, ip in hostinfo.ips ~}
    ${ip}:
      hostname_short: ${ hostinfo.hostnames_short[index] }
      hostname_long: ${ hostinfo.hostnames_long[index] }
%{ endfor ~}%{ endfor ~}

  children:
    crdb_client:
      children:
%{ for cluster, hostinfo in crdb_client_servers ~}
        crdb_client_cluster_${cluster}:
          hosts:
%{ for index, ip in hostinfo.ips ~}
            ${ip}:
%{ endfor ~}
%{ endfor ~}
    crdb:
      children:
%{ for cluster, hostinfo in crdb_servers ~}
        crdb_cluster_${cluster}:
          hosts:
%{ for index, ip in hostinfo.ips ~}
            ${ip}:
%{ endfor ~}
%{ endfor ~}

#
# EOF
#
