---
- name: extend root lvm partition
  include: extend_lvm.yml

- name: update the kernel
  include: update_kernel.yml

- name: configure limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    block: |
      *              soft     nofile          65536
      *              hard     nofile          65536
  notify:
    - reboot_machine