---
- name: Delete all test databases
  hosts:
    - crdb_client[0]
  gather_facts: no
  any_errors_fatal: true

  vars:
    databases:
      - bank
      - tpcc
      - ycsb
    crdb_db_port: 26257
    crdb_servers: "{{ hostvars['localhost']['groups']['crdb'] }}"
    db_settings:
      - "SET CLUSTER SETTING rocksdb.ingest_backpressure.l0_file_count_threshold = 20"            # Def. 20
      - "SET CLUSTER SETTING rocksdb.ingest_backpressure.pending_compaction_threshold = '2 GiB'"  # Def. 2.0 GiB
      - "SET CLUSTER SETTING schemachanger.backfiller.max_buffer_size = '512 MiB'"                # Def. 512 MiB
      - "SET CLUSTER SETTING kv.snapshot_rebalance.max_rate = '8 MiB'"                            # Def. 8.0 MiB
      - "SET CLUSTER SETTING rocksdb.min_wal_sync_interval = '00:00:00'"                          # Def. 00:00:00
      - "ALTER RANGE default CONFIGURE ZONE USING num_replicas = 3"
  
  tasks:
    - name: Delete databases
      shell: "cockroach sql --url='postgres://root@{{ crdb_servers[0] }}:{{ crdb_db_port }}?sslmode=disable' --execute='DROP DATABASE IF EXISTS {{ item }}'"
      loop: "{{ databases }}"
      
    - name: Reset default database settings
      shell: "cockroach sql --url='postgres://root@{{ crdb_servers[0] }}:{{ crdb_db_port }}?sslmode=disable' --execute=\"{{ item }}\""
      loop: "{{ db_settings }}"
