---
- name: Common configuration
  hosts:
    - crdb
    - crdb_client
  roles:
    - common
    - cockroach

- name: Cockroach workload
  hosts:
    - crdb_client
  roles:
    - workload

- name: CockroachDB servers
  hosts: 
    - crdb
  roles:
    - crdb
