---
- name: Common configuration
  hosts:
    - crdb
    - crdb_client
  roles:
    - common
    - cockroach

- name: Build and load PTP driver
  hosts:
    - crdb
    - crdb_client
  roles:
    - ptp_driver

- name: Install and configure Chrony
  hosts:
    - crdb
    - crdb_client
  roles:
    - chrony

- name: Cockroach workload
  hosts:
    - crdb_client
  roles: 
    - workload

- name: CockroachDB servers
  hosts: crdb
  roles: 
    - crdb

- name: CockroachDB license
  hosts: crdb[0]
  roles:
    - crdb_license
