---
- name: Common configuration
  hosts:
    - crdb
    - crdb_haproxy
    - crdb_client
  roles:
    - common
    - cockroach

- name: Install PTP driver and chronyd
  hosts:
    - crdb
    - crdb_haproxy
    - crdb_client
  roles:
    - ptp_driver
    - chrony

- name: Cockroach workload binary
  hosts:
    - crdb_client
  roles: 
    - workload

- name: CockroachDB service
  hosts: crdb
  roles: 
    - crdb

- name: CockroachDB license
  hosts: crdb[0]
  roles:
    - crdb_license

- name: HA Proxy
  hosts: crdb_haproxy
  vars:
    crdb_node: "{{ hostvars['localhost']['groups']['crdb'][0] }}"
  roles:
    - crdb_haproxy
